const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const {groupedLayout}=require('./layout');
let config={columns:3,rows:3,buttons:[{id:'a',slot:0},{id:'b',slot:1},{id:'c',slot:3}]},commits=[],timer;
const events={},windows={},docEvents={};
const cls=()=>{const s=new Set();return {add:(...v)=>v.forEach(x=>s.add(x)),remove:(...v)=>v.forEach(x=>s.delete(x)),toggle:(v,on)=>on?s.add(v):s.delete(v),contains:v=>s.has(v)};};
const els=config.buttons.map(b=>({dataset:{button:b.id},style:{slot:b.slot},classList:cls()}));
const deck={classList:cls(),addEventListener:(n,f)=>events[n]=f,setPointerCapture(){},getBoundingClientRect:()=>({left:0,top:0,right:300,bottom:300,width:300,height:300}),querySelectorAll:s=>s==='[data-button]'?els:s==='.group-selected'?els.filter(e=>e.classList.contains('group-selected')):[]};
const context={structuredClone,Set,Math,JSON,setTimeout:f=>{timer=f;return 1;},clearTimeout(){},groupedLayout,applyGridStyle:(el,b)=>el.style.slot=b.slot,message(){},window:{addEventListener:(n,f)=>windows[n]=f},document:{addEventListener:(n,f)=>docEvents[n]=f}};
vm.createContext(context);vm.runInContext(fs.readFileSync('reorder.js','utf8'),context);
context.installPreviewReorder(deck,{config:()=>config,ids:()=>['a','b'],commit:next=>commits.push(next)});
const ev=(x,y)=>({button:0,pointerId:1,clientX:x,clientY:y,target:{closest:()=>els[0]},preventDefault(){}});
const begin=()=>{events.pointerdown(ev(50,50));timer();};
begin();events.pointermove(ev(50,150));assert.equal(commits.length,0);assert.deepEqual(els.map(e=>e.style.slot),[3,4,0]);
events.pointermove(ev(50,50));assert.deepEqual(els.map(e=>e.style.slot),[0,1,3]);
events.pointermove(ev(50,150));const preview=els.map(e=>e.style.slot);events.pointerup(ev(50,150));assert.deepEqual(commits[0].buttons.map(b=>b.slot),preview);
begin();events.pointermove(ev(50,150));events.pointercancel();assert.equal(commits.length,1);assert.deepEqual(els.map(e=>e.style.slot),[0,1,3]);
begin();events.pointermove(ev(250,250));events.pointerup(ev(250,250));assert.equal(commits.length,1);
begin();events.pointermove(ev(50,150));config.revision=2;events.pointerup(ev(50,150));assert.equal(commits.length,1);
begin();events.pointermove(ev(50,150));windows['deck:viewchange']();assert.deepEqual(els.map(e=>e.style.slot),[0,1,3]);
begin();events.pointermove(ev(50,150));events.pointerup(ev(400,150));assert.equal(commits.length,1);
console.log('Preview: full reflow, no early writes, roundtrip, exact commit, cancel, out-of-bounds, concurrent change, view change OK');
